In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [4]:
df=pd.read_csv('gurgaon_properties.csv')

In [5]:
df.tail()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3956,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,0.98,6049.0,1620.0,Super Built up area 1620(150.5 sq.m.),3,3,3,study room,"Sector 71 Gurgaon, Gurgaon, Haryana",0.0,South-East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Chd avenue 71 sector 71 is good project\n Addi...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction3 out of..."
3957,3 BHK Flat in Sector 65 Gurgaon,flat,emaar mgf emerald floors premier,2.35,14242.0,1650.0,Carpet area: 1650 (153.29 sq.m.),3,3,3,"study room,servant room","698, Sector 65 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...",Emaar mgf emerald floors premier is one of gur...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction5 out ..."
3958,3 BHK Flat in Sector 1 Gurgaon,flat,the nav manesar apartment,0.85,3953.0,2150.0,Super Built up area 2150(199.74 sq.m.),3,3,3+,servant room,"Sector 1 Gurgaon, Gurgaon, Haryana",5.0,North-East,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Nav manesar gh-20 good property imt manesar .....,NaN,"['Feng Shui / Vaastu Compliant', 'Piped-gas']",NaN
3959,3 BHK Flat in Sector 74 Gurgaon,flat,m3m skywalk,2.45,12140.0,2018.0,Super Built up area 2018(187.48 sq.m.)Built Up...,3,3,3+,study room,"T2-1111, Sector 74 Gurgaon, Gurgaon, Haryana",25.0,South-West,1 to 5 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",This lovely 3 bhk apartment/flat in sector 74 ...,NaN,"['Centrally Air Conditioned', 'Security / Fire...",NaN
3960,2 Bedroom House for sale in Sector 31 Gurgaon,house,project housing board colony,8.00,63492.0,1260.0,Built Up area: 140 (117.06 sq.m.),2,1,0,not available,"Sector 31, Sector 31 Gurgaon, Gurgaon, Haryana",1.0,NaN,undefined,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...",2bhk residential house for resale in project h...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [11]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [12]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,New Colony,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,Sector 14,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,Sector 113,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,DLF Phase 2,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,DLF Phase 3,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [13]:
df['sector']=df['sector'].str.lower()

In [14]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,new colony,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,dlf phase 2,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,dlf phase 3,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [15]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
dlf phase 3                                                   22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
dlf phase 5                                                   14
gwal pahari                                                   14
sector 3                                                      14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 53                                                     14
sector 76                                                     14
rajendra park                                                 14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 39                                                     12
sector 38                                                     12
uppals southend                                               12
sohna road                                                    12
sector 31                                                     12
sector 93                                                     12
sector 50                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 55                                                      9
sector 4                                                       9
ashok vihar phase 2                                            9
sector 95a                                                     9
south city 1                                                   9
sector 89 a                                                    8
sector 57                                                      8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 43                                                      8
malibu town                                                    8
sector 40                                                      8
palam vihar extension                                          8
sector 59                                                      8
sector 10a                                                     8
sector 51                                                      7
sector 11                                                      7
new colony                                                     7
sector 36 sohna                                                7
sector 26                                                      7
mianwali colony                                                7
surat nagar 1                                                  7
sector 58                                                      7
sector 5                                                       6
jyoti park                                                     6
sector 1                                                       6
ashok vihar                                                    6
jacobpura                                                      6
rajiv nagar                                                    6
manesar                                                        5
sector 23a                                                     5
sector 28                                                      5
subhash nagar                                                  5
saraswati vihar                                                5
sector 2                                                       5
sector 30                                                      5
sector 80                                                      5
sector 9                                                       5
chakkarpur                                                     5
greenwood city                                                 5
sushant lok phase 2                                            5
sector 105                                                     5
ansal plaza                                                    5
new palam vihar                                                5
dayanand colony                                                5
arjun nagar                                                    5
devilal colony                                                 4
surya vihar                                                    4
shivpuri                                                       4
imt manesar                                                    4
madanpuri                                                      4
bhim nagar                                                     4
adarsh nagar                                                   4
sector 45                                                      4
valley view estate                                             4
garhi harsaru                                                  4
new                                                            4
sector 3a                                                      4
sector 12a                                                     4
sector 6                                                       4
krishna colony                                                 4
sector 12                                                      4
suncity                                                        4
sector 17                                                      4
dharam colony                                                  4
ravi nagar                                                     4
sector 36                                                      4
bhondsi                                                        4
shivaji nagar                                                  4
vishnu garden                                                  4
baldev nagar                                                   4
prem nagar                                                     3
a block sushant lok phase 1                                    3
sector 110 a                                                   3
sector 17a                                                     3
maruti kunj                                                    3
sector 15                                                      3
b block sushant lok phase 1                                    3
mg road                                                        3
sector 23                                                      3
laxmi garden                                                   3
sector 27                                                      3
sector 17b                                                     3
shakti nagar                                                   3
patel nagar                                                    3
sector 8                                                       3
sector 73                                                      3
sector 88b                                                     3
gandhi nagar                                                   3
shankar vihar                                                  2
rajiv chowk                                                    2
iffco chowk                                                    2
sector 15 part 2                                               2
west rajiv nagar                                               2
daulatabad                                                     2
sector-2 sohna                                                 2
sector 15 part 1                                               2
mohan nagar                                                    2
new basti                                                      2
sector 41                                                      2
, delhi ncr                                                    2
samaspur                                                       2
new palam vihar phase 2                                        2
golf course ext road                                           2
sector-11 sohna                                                2
farukhnagar                                                    2
sector 21                                                      2
manohar nagar                                                  2
pratap nagar                                                   2
bissar                                                         2
surat nagar                                                    2
ambience island                                                2
sector 32                                                      2
surat nagar phase 2                                            2
new palam vihar phase 1                                        2
golf course road                                               2
nars                                                           2
hira nagar                                                     2
sohna  road                                                    2
lajpat nagar                                                   2
rosewood                                                       2
shanti nagar                                                   2
bhawani enclave                                                2
sheetla colony                                                 2
sector 24                                                      2
sispal vihar                                                   2
block a surya vihar                                            2
acharya puri                                                   2
mayfield garden                                                2
faridabad road                                                 2
sushant lok                                                    2
near khandsa road                                              1
damdma                                                         1
pataudi road                                                   1
ravi nager basai road                                          1
naharpur rupa                                                  1
gopal nagar, garhi ghasita, sonipat                            1
sector 37b                                                     1
udyog vihar phase 1                                            1
devi lal colony gali no 12 gurgaon nr omkar public school      1
laxmna vihar, phase 2                                          1
sector-7 hous                                                  1
rajiv colony                                                   1
bptp                                                           1
sector 5 chowk                                                 1
lucknow                                                        1
sector 4 urban estate                                          1
b1 block sector 57                                             1
khandsa                                                        1
near pataudi chowk                                             1
sector-35 sohna                                                1
bhimgarh kheri phase 3                                         1
alipur                                                         1
hno 13 sagar enclave sura                                      1
sector 42                                                      1
sultanpur                                                      1
sai kunj                                                       1
sector 21a faridabad                                           1
near nand hospital                                             1
rattan garden                                                  1
hsiidc plot sector 1 imt manesar                               1
near euro                                                      1
sector 13                                                      1
sector 37a                                                     1
sadar bazar                                                    1
old delhi road, opp sector-14                                  1
part 3 sector 5                                                1
cyber city                                                     1
ats marigold                                                   1
ashok vihar phase 3                                            1
om nagar                                                       1
new colony, sector 7                                           1
ashok vihar phase i                                            1
bhora kalan                                                    1
block g sector-57                                              1
saraswati enclave                                              1
tekchand nagar                                                 1
sector-5 sheetla colony                                        1
urban estate, sector 5                                         1
new jyoti park                                                 1
sector 9b                                                      1
dhankot                                                        1
begampur khatola                                               1
civil l                                                        1
laxman vihar, railway road,                                    1
near sector 1 market                                           1
anand garden, sector-105                                       1
shivji park colony                                             1
jacobpura near sadar bazar                                     1
garauli kalan                                                  1
vir nagar                                                      1
sector-5 sohna                                                 1
huda saraswati vihar                                           1
kanahi                                                         1
nirvana country pocket h                                       1
mahavir pura                                                   1
heritage city                                                  1
ram nagar                                                      1
jat colony,fazilpur/taj nagar road                             1
sector 17c                                                     1
g block dlf city phase 1                                       1
v block dlf phase 3                                            1
park view                                                      1
godrej aria , sector 79 ,                                      1
south city                                                     1
block h ashok vihar phase iii extension                        1
kheri                                                          1
carterpuri village                                             1
ansal's palam vihar                                            1
mahalaxmi garden, rajendra place                               1
saroop garden rajendra park                                    1
sec 3 bhim vihar part 1 bhimgher kheri                         1
Name: sector, dtype: int64

In [16]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [17]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,sector 7,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,sector 25,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,sector 24,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [28]:
a=df['sector'].value_counts()[df['sector'].value_counts()>= 3]
df=df[df['sector'].isin(a.index)]

In [30]:
df['sector'].value_counts()

sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 81                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 37c                     53
sector 70                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 24                      24
sector 112                     24
sector 105                     23
sector 14                      23
sector 33                      23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 22                      20
sector 3                       20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 52                      14
sector 76                      14
sector 55                      14
sector 1 manesar               14
sector 53                      14
sector 4 phase 2               13
sector 9                       13
sector 46                      13
sector 6                       13
sector 36a                     13
sector 31                      12
sector 93                      12
sector 38                      12
sector 39                      12
sohna road road                12
sector 9a                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 1a manesar              10
sector 13                      10
sector 3 phase 2                9
manesar                         9
sector 95a                      9
sector 45                       9
sector 17                       8
sector 59                       8
sector 10a                      8
sector 89 a                     8
dwarka expressway               8
c block sector 43               8
sector 2 extension              8
sector 23                       8
sector 8                        8
sector 40                       8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 5                        6
sector 21                       6
sector 1                        6
new sector 2                    5
sector 30                       5
sector 80                       5
sector 23a                      5
new                             4
sector 36                       4
sector 12a                      4
sector 3a                       4
sector 17b                      3
sector 88b                      3
sector 73                       3
a block sector 43               3
sector 110 a                    3
b block sector 43               3
patel nagar                     3
sector 15                       3
sector 27                       3
sector 17a                      3
maruti kunj                     3
Name: sector, dtype: int64

In [31]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [32]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [33]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1486,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2236,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2630,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3221,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [39]:
df.loc[1486,'sector']= 'sector 76'
df.loc[2236,'sector']= 'sector 90'
df.loc[2630,'sector']= 'sector 92'
df.loc[3221,'sector']= 'sector 37'

In [41]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
332,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
705,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1115,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2006,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2292,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [44]:
df.loc[[332,705,1115,2006,2292],'sector']='sector 110'

In [45]:
df.shape

(3803, 21)

In [47]:
df.duplicated().sum()

0

In [48]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,sector 7,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,sector 25,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,sector 24,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [51]:
df.drop(columns=['property_name','address','description','rating'],inplace=True)

In [53]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
276,flat,tulip violet,sector 69,1.60,10139.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,0.0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F..."
991,house,independent,sector 45,17.00,37777.0,4500.0,Plot area 4500(418.06 sq.m.),5,8,3+,"pooja room,study room,servant room,store room",3.0,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...","['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'..."
3375,flat,apna enclave,sector 3,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
1042,flat,pooja apartment,sector 3 phase 3 extension,0.25,3571.0,700.0,Carpet area: 700 (65.03 sq.m.),2,2,2,not available,2.0,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['2 Fan', '2 Geyser', '6 Light', '1 Chimney', ...",NaN
172,flat,shapoorji pallonji joyville gurugram,sector 102,1.76,10224.0,1721.0,Super Built up area 1692(157.19 sq.m.),3,3,3,not available,1.0,North-East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [57]:
df[df.duplicated()]

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
384,flat,siddhartha apartment,sector 95,1.10,4327.0,2542.0,Carpet area: 2542 (236.16 sq.m.),4,3,3,"servant room,others",9.0,North,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
551,flat,shapoorji pallonji joyville gurugram,sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 8...,2,2,2,not available,14.0,North-West,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
659,flat,signature global city 63a,sector 63a,1.40,11336.0,1235.0,Carpet area: 1235 (114.74 sq.m.),2,2,2,others,3.0,East,Jul 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",[],NaN
837,flat,bhagwati sadan,sector 12,1.15,5500.0,2091.0,Built Up area: 2000 (185.81 sq.m.),3,4,2,"servant room,others",2.0,NaN,10+ Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
919,flat,ss almeria,sector 84,1.48,7400.0,2000.0,Super Built up area 2000(185.81 sq.m.)Carpet a...,3,3,2,"servant room,store room",1.0,South-West,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH ...","['3 Wardrobe', '5 Fan', '3 Geyser', '1 Stove',...","['Security / Fire Alarm', 'Private Garden / Te..."
1023,flat,smart world gems,sector 89,0.95,8600.0,1105.0,Carpet area: 1103 (102.47 sq.m.),2,2,2,"study room,servant room",4.0,NaN,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s..."
1049,flat,eldeco accolade,sector 33,1.20,8043.0,1492.0,Built Up area: 1492 (138.61 sq.m.)Carpet area:...,2,2,2,not available,0.0,NaN,undefined,"['Global City Centre', 'Sohna Road', 'Damdama ...",NaN,NaN
1058,flat,ild greens,sector 37c,0.90,5614.0,1603.0,Super Built up area 1603(148.92 sq.m.)Built Up...,3,3,3,not available,0.0,North-East,Under Construction,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...",NaN,"['Lift(s)', 'Feng Shui / Vaastu Compliant', 'I..."
1061,flat,apartment,sector 92,0.75,4687.0,1600.0,Carpet area: 1600 (148.64 sq.m.),3,4,3,study room,2.0,East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","['5 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1079,flat,ramsons kshitij,sector 95,0.33,3911.0,844.0,Super Built up area 767(71.26 sq.m.),2,2,1,others,14.0,South,0 to 1 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...","['2 Bed', '1 Wardrobe', '3 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1209,flat,unitech uniworld gardens,sector 47,1.05,10531.0,997.0,Carpet area: 997 (92.62 sq.m.),2,2,2,not available,3.0,North-East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...","['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1223,flat,birla navya,sector 63a,3.70,15416.0,2400.0,Carpet area: 2400 (222.97 sq.m.),3,3,3+,not available,1.0,North,By 2024,"['Sector 54 Chowk Metro Station', 'WorldMark G...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1335,flat,umang monsoon breeze,sector 78,1.15,5284.0,2176.0,Super Built up area 2176(202.16 sq.m.),3,3,3,"servant room,others",9.0,NaN,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",NaN,"['Security / Fire Alarm', 'Intercom Facility',..."
1342,flat,maruti vihar,sector 28,1.00,9090.0,1100.0,Super Built up area 1100(102.19 sq.m.),1,1,1,"pooja room,study room",1.0,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","['6 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."
1404,flat,umang monsoon breeze,sector 78,0.75,6053.0,1239.0,Built Up area: 1239 (115.11 sq.m.)Carpet area:...,2,2,1,not available,5.0,East,undefined,"['Proposed Metro Station', 'Mahapal Shing', 'N...",NaN,NaN
1425,flat,unitech heritage city,sector 14,4.26,13108.0,3250.0,Built Up area: 3250 (301.93 sq.m.),4,4,0,not available,9.0,NaN,undefined,"['Mg road metro station', 'Iffco chowk metro s...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
1439,flat,smart world gems,sector 89,1.71,12000.0,1425.0,Built Up area: 1423 (132.2 sq.m.),3,2,0,not available,3.0,NaN,undefined,"['Sant Soordas Sihi Metro Station', 'Airia Mal...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
1498,flat,dlf carlton estate,sector 43,2.00,14214.0,1407.0,Super Built up area 1407(130.71 sq.m.),3,3,2,not available,5.0,South-West,5 to 10 Year Old,"['Sector 53-54', 'South Point Mall', 'United C...","['2 Wardrobe', '1 Sofa', '2 Geyser', '2 AC', '...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1523,flat,godrej air,sector 85,1.05,10603.0,990.0,Built Up area: 97 Carpet area: 92 sq.m.,2,2,1,not available,15.0,East,Jan 2024,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
1617,flat,assotech blith,sector 99,1.90,6702.0,2835.0,Built Up area: 2835 (263.38 sq.m.),4,4,3+,not available,2.0,North-East,undefined,"['Huda Metro Station (Gurugram)', 'Dwarka Expr...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
1628,flat,emaar mgf palm hills,sector 77,1.25,8620.0,1450.0,Carpet area: 1450 (134.71 sq.m.),3,4,3,servant room,1.0,West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1644,flat,sapphire eighty three,sector 83,0.65,9286.0,700.0,Built Up area: 700 (65.03 sq.m.),1,1,0,not available,6.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Or...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
1660,flat,assotech blith,sector 99,0.92,6739.0,1365.0,Super Built up area 1365(126.81 sq.m.),2,2,3+,not available,22.0,NaN,By 2023,"['Huda Metro Station (Gurugram)', 'Dwarka Expr...",[],"['Private Garden / Terrace', 'Lift(s)', 'Swimm..."
1752,flat,indiabulls enigma,sector 110,4.00,9851.0,4061.0,Built Up area: 3350 (311.23 sq.m.),4,4,3,not available,17.0,NaN,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",NaN,NaN
1785,flat,gls arawali homes,sohna road,0.35,7000.0,500.0,Super Built up area 567(52.68 sq.m.)Built Up a...,2,2,2,not available,5.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
1967,flat,emaar gurgaon greens,sector 102,1.35,8181.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,servant room,5.0,North-West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1980,flat,ats tourmaline,sector 109,2.30,8897.0,2585.0,Super Built up area 2585(240.15 sq.m.),3,4,3+,"servant room,others",10.0,East,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",[],"['Feng Shui / Vaastu Compliant', 'Security / F..."
1985,flat,ild grand,sector 37c,0.66,5038.0,1310.0,Built Up area: 1310 (121.7 sq.m.),2,2,3+,not available,14.0,NaN,undefined,"['The Esplanade Mall', 'Dwarka Expy, Sector 88...",NaN,NaN
2049,flat,mvn athens,sohna road,0.24,7056.0,340.0,Carpet area: 340.09 (31.6 sq.m.),1,1,1,not available,12.0,West,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...","['2 Fan', '1 Dining Table', '1 Geyser', '3 Lig...","['Lift(s)', 'High Ceiling Height', 'Maintenanc..."
2068,flat,sidhivinayak apartments,sector 55,1.90,10555.0,1800.0,Carpet area: 1800 (167.23 sq.m.),4,3,3+,pooja room,9.0,North,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...","['1 Water Purifier', '1 Fridge', '10 Fan', '1 ...","['Intercom Facility', 'Lift(s)', 'Maintenance ..."
2125,flat,sare crescent parc,sector 92,0.82,5384.0,1523.0,Built Up area: 1523 (141.49 sq.m.),3,3,3+,not available,12.0,West,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2153,flat,experion windchants,sector 112,5.60,11529.0,4857.0,Super Built up area 4857(451.23 sq.m.)Built Up...,4,6,3+,servant room,15.0,North-East,5 to 10 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['5 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
2160,flat,silverglades the melia,sohna road,0.75,5555.0,1350.0,Built Up area: 1350 (125.42 sq.m.),2,2,2,not available,4.0,NaN,5 to 10 Year Old,"['Global City Centre Mall', 'Sohna Road', 'Wes...",[],NaN
2201,flat,dlf the grove,sector 54,5.70,41245.0,1382.0,Built Up area: 1382 (128.39 sq.m.),3,3,3,not available,1.0,East,undefined,"['Sector 54 chowk metro station', 'Sector 53-5...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
2267,flat,signature the roselia,sector 95,0.45,7908.0,569.0,Carpet area: 569 (52.86 sq.m.),2,2,2,not available,2.0,East,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","['4 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
2275,flat,godrej,sector 79,1.29,8206.0,1572.0,Super Built up area 1572(146.04 sq.m.),2,2,3,not available,4.0,NaN,0 to 1 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",NaN,NaN
2277,flat,mrg world ultimus,sector 90,0.50,6983.0,716.0,Carpet area: 716 (66.52 sq.m.),2,2,2,not available,1.0,North-East,Mar 2024,"['Huda Metro Station', 'Aanyaz Mall', 'Sector ...",NaN,"['Lift(s)', 'Maintenance Staff', 'Water Storag..."
2297,flat,ansal heights 86,sector 86,0.90,5325.0,1690.0,Built Up area: 1690 (157.01 sq.m.),3,3,2,not available,10.0,NaN,0 to 1 Year Old,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Security / Fire Alarm', 'Intercom Facility',..."
2307,flat,dhoot time residency,sector 63,3.00,18271.0,1642.0,Built Up area: 1642 (152.55 sq.m.)Carpet area:...,3,3,3+,servant room,14.0,NaN,1 to 5 Year Old,"['Metro Station', 'High end group housing', 'N...","['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...",NaN
2319,flat,sukhshanti apartment,sector 56,1.70,7727.0,2200.0,Built Up area: 2200 (204.39 sq.m.)Carpet area:...,3,3,3,study room,4.0,South,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F..."
2355,flat,antriksh heights,sector 84,0.85,5556.0,1530.0,Super Built up area 1350(125.42 sq.m.),2,2,3,"study room,others",10.0,North-West,0 to 1 Year Old,"['Old Bengali Market', 'MatriKiran High School...",NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ..."
2381,flat,ramprastha the edge towers,sector 37d,0.80,5797.0,1380.0,Super Built up area 1380(128.21 sq.m.)Built Up...,2,2,3,not available,2.0,North-East,1 to 5 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...","['5 Fan', '2 Geyser', '7 Light', '2 Wardrobe',...","['Security / Fire Alarm', 'Intercom Facility',..."
2413,flat,emaar imperial gardens,sector 102,1.98,9900.0,2000.0,Carpet area: 2000 (185.81 sq.m.),3,3,3+,servant room,9.0,North,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
2428,flat,ambience caitriona,sector 24,14.00,200000.0,700.0,Built Up area: 700 (65.03 sq.m.),4,5,3,not available,3.0,East,undefined,"['Dlf phase 3 metro station', 'Micromax moulsa...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2451,flat,sare crescent parc,sector 92,0.49,4909.0,998.0,Carpet area: 998 (92.72 sq.m.),2,2,2,not available,2.0,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2467,flat,shapoorji pallonji joyville gurugram,sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 6...,2,2,2,not available,14.0,NaN,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2477,flat,vatika sovereign park,sector 99,3.20,9922.0,3225.0,Built Up area: 3225 (299.61 sq.m.),4,4,0,not available,5.0,North-East,Dec 2023,"['The Esplanade Mall', 'Dwarka Expressway', 'K...",NaN,"['Swimming Pool', 'Water Storage', 'Park', 'Cl..."
2488,flat,avl 36 gurgaon,sector 36a,0.75,7500.0,1000.0,Super Built up area 1000(92.9 sq.m.)Carpet are...,2,2,2,not available,5.0,North-East,1 to 5 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Sh...","['1 Wardrobe', '3 Fan', '6 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
2493,flat,essel towers,sector 14,2.20,12500.0,1760.0,Carpet area: 1760 (163.51 sq.m.),3,4,3+,not available,3.0,NaN,undefined,"['Mg road metro station', 'Iffco chowk metro s...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
2499,flat,tulip petals,sector 89,1.55,10000.0,1550.0,Super Built up area 1550(144 sq.m.),3,2,3,store room,6.0,East,5 to 10 Year Old,"['IRIS Broadway Mall', 'Pataudi Road', 'Dwarka...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2534,flat,ireo the corridors,sector 67a,1.50,11111.0,1350.0,Carpet area: 1350 (125.42 sq.m.),2,2,2,store room,10.0,NaN,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 St...","['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
2537,flat,ansal housing highland park,sector 103,0.88,6429.0,1369.0,Super Built up area 1361(126.44 sq.m.),2,2,3,not available,3.0,NaN,0 to 1 Year Old,"['State bank ATM', 'Dr. Hitesh Dawar', 'Bhardw...",NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
2540,flat,eldeco accolade,sohna road,1.10,7549.0,1457.0,Super Built up area 1457(135.36 sq.m.),2,2,3+,"study room,others",17.0,NaN,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","['1 Water Purifier', '1 Exhaust Fan', '2 Geyse...",['Visitor Parking']
2635,flat,breez global hill view,sohna road,0.35,6315.0,554.0,Carpet area: 554.16 (51.48 sq.m.),2,2,2,not available,14.0,West,0 to 1 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",[],"['Power Back-up', 'Security / Fire Alarm', 'Li..."
2644,flat,tulip ivory,sector 70,5.00,10416.0,4800.0,Carpet area: 4800 (445.93 sq.m.),6,7,3+,"study room,servant room",0.0,NaN,1 to 5 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...",[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2660,flat,essel towers,sector 14,2.20,12500.0,1760.0,Carpet area: 1760 (163.51 sq.m.),3,4,3+,not available,3.0,North-West,undefined,"['Mg road metro station', 'Iffco chowk metro s...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
2661,flat,signature global park,sohna road,0.68,8252.0,824.0,Carpet area: 824 (76.55 sq.m.),2,2,2,not available,3.0,NaN,Within 6 months,"['Sector 55-56 metro', 'Global city centre', '...","['2 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2668,flat,brisk lumbini terrace homes,sector 109,1.50,6616.0,2267.0,Carpet area: 2267 (210.61 sq.m.),3,3,1,servant room,4.0,North,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Ram Mandir', 'K...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
2692,flat,mvn athens,sohna road,0.26,5397.0,482.0,Carpet area: 481.73 (44.75 sq.m.),2,2,1,not available,5.0,NaN,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...","['1 Bed', '3 Fan', '1 Sofa', '7 Light', '1 Cur...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2696,flat,ramsons kshitij,sector 95,0.40,5839.0,685.0,Carpet area: 685 (63.64 sq.m.),3,2,2,not available,6.0,NaN,undefined,NaN,NaN,NaN
2706,flat,essel tower,sector 28,2.20,12500.0,1760.0,Carpet area: 1760 (163.51 sq.m.),3,4,3+,servant room,3.0,NaN,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...",NaN
2746,flat,signature global park,sohna road,0.54,7248.0,745.0,Carpet area: 745 (69.21 sq.m.),2,1,3,not available,1.0,NaN,Within 6 months,"['Sector 55-56 metro', 'Global city centre', '...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2757,flat,ireo victory valley,sector 67,3.49,13000.0,2685.0,Carpet area: 2452 (227.8 sq.m.),3,3,3,servant room,19.0,South-East,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2760,flat,godrej oasis,sector 88a,2.65,16747.0,1582.0,Carpet area: 124,3,3,3+,not available,10.0,NaN,0 to 1 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...","['1 Exhaust Fan', '1 Stove', '1 Light', '1 AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2783,flat,railway officers rpf society,sector 9a,1.25,6921.0,1806.0,Carpet area: 1806 (167.78 sq.m.),4,3,3,servant room,1.0,South-West,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...","['3 Wardrobe', '1 Exhaust Fan', '3 Geyser', '1...","['Power Back-up', 'Feng Shui / Vaastu Complian..."
2800,flat,green court,sector 90,0.47,6811.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,0.0,East,0 to 1 Year Old,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","['3 Fan', '1 Exhaust Fan', '7 Light', 'No AC',...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2802,flat,the close north,sector 50,3.00,11516.0,2605.0,Super Built up area 2605(242.01 sq.m.),3,3,3+,servant room,14.0,North,10+ Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","['3 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2834,flat,surendra avenue 69,sector 69,0.75,6818.0,1100.0,Built Up area: 1100 (102.19 sq.m.),2,2,2,not available,4.0,NaN,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","['1 Bed', '1 Wardrobe', '1 Fan', '1 Sofa', '1 ...",NaN
2836,flat,sare green parc phase 3,sector 92,0.95,4856.0,1956.0,Super Built up area 1956(181.72 sq.m.),4,3,3,not available,4.0,North,5 to 10 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",NaN,"['Security / Fire Alarm', 'Intercom Facility',..."
2866,flat,conscient habitat,sector 99a,0.35,6422.0,545.0,Carpet area: 545 (50.63 sq.m.),2,2,1,not available,3.0,North-East,1 to 5 Year Old,NaN,"['2 Fan', '1 Washing Machine', '6 Light', '1 A...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
2868,flat,m3m skycity,sector 65,3.50,17039.0,2054.0,Carpet area: 2054 (190.82 sq.m.),3,3,3,"pooja room,study room,servant room",15.0,East,Within 3 months,"['Sector 55 Metro Station', 'Eros City Square'...","['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'..."
2891,flat,emaar digihomes,sector 62,2.15,14257.0,1508.0,Carpet area: 1508 (140.1 sq.m.),2,2,3,not available,31.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",NaN,"['Security / Fire Alarm', 'Intercom Facility',..."
2959,flat,signature global city 37d ph 2,sector 37d,1.36,8846.0,1537.0,Built Up area: 1535 (142.61 sq.m.),3,3,3,"pooja room,others",1.0,North-East,Oct 2025,"['Dwarka Expressway', 'Pataudi Road', 'Euro In...",[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
2968,flat,godrej summit,sector 104,0.82,9854.0,832.0,Carpet area: 77.31,2,2,3,study room,12.0,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2980,flat,bestech park view residency,sector 2,1.40,7865.0,1780.0,Super Built up area 1780(165.37 sq.m.),3,3,3+,not available,6.0,North,10+ Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...","['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
3008,flat,unitech vistas,sector 70,0.53,4800.0,1104.0,Super Built up area 1095(101.73 sq.m.),2,2,2,others,9.0,NaN,Mar 2024,"['Airia Mall', 'Delhi Ajmer Highway', 'Sohna R...",[],"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ..."

In [ ]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)