In [1]:
import numpy as np 
import pandas as pd

In [2]:
flats=pd.read_csv("flats_cleaned.csv")
house=pd.read_csv("house_cleaned.csv")

In [3]:
df=pd.concat([flats,house],ignore_index=True)

In [5]:
df=df.sample(df.shape[0],ignore_index=True)

In [7]:
df.head(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in New Colony,house,independent,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,"394/1/11, New Colony, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",50meter away famous market with omsweets\nSubw...,[],['Park'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 Bedroom House for sale in Sector 14 Gurgaon,house,independent,5.00,22222.0,2250.0,Plot area 250(209.03 sq.m.),3,3,3,not available,"Sector 14 Gurgaon, Gurgaon, Haryana",1.0,South,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",Are you planning to buy your dream home? You c...,NaN,"['Private Garden / Terrace', 'No open drainage...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,2.78,10334.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3+,servant room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3,12 Bedroom House for sale in DLF Phase 2,house,independent,NaN,NaN,NaN,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12,12,3+,"pooja room,study room,servant room,others","DLF Phase 2, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,4 Bedroom House for sale in DLF Phase 3,house,dlf city plots phase 3,1.44,26667.0,540.0,Plot area 60(50.17 sq.m.),4,2,2,not available,"S Block, DLF Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [12]:
df.to_csv('gurgaon_properties.csv',index=False)

(3961, 20)